export enum DataApiQueryType {
  FIRST_OR_LAST = 'FIRST_OR_LAST',
  AGGREGATE = 'AGGREGATE',
  HISTORICAL = 'HISTORICAL',
  LATEST_QUOTE = 'LATEST_QUOTE',
  MOST_USED = 'MOST_USED',
  TRADING_PAIRS = 'TRADING_PAIRS',
  PORTFOLIO = 'PORTFOLIO',
}
